import Head from 'next/head'
import { ReactNode } from 'react'

interface Props {
  children?: ReactNode
}

const Layout = ({ children }: Props) => {
  return (
    <div className="flex flex-col min-h-screen">
      <Head>
        <title>UI/UX Training</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex-1">{children}</main>
      <footer></footer>
    </div>
  )
}

export default Layout
