import '@/styles/globals.css'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="debug-screens scroll-smooth">
      <head>
        <title>UI/UX Training</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className="flex min-h-screen w-full flex-col bg-blue-50">
        <main className="flex-1">{children}</main>
        <footer></footer>
      </body>
    </html>
  )
}
